# Python 3.7 is only on Xenial
dist: xenial

language: python
python:
   - "3.7.3"

before_install:
  - pip install pipenv

install:
  - pipenv install

jobs:
  include:
    - stage: "Tests"
      name: "Build site"
      script: mkdocs build --verbose --clean --strict